global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ecologic_optimizer"
    static_configs:
      - targets: ["optimizer:8000"]
    metrics_path: /metrics

  - job_name: "mysql"
    static_configs:
      - targets: ["mysql:3306"]
